swagger: '2.0'
info:
  title: Movie API
  version: 1.0.0
description: An API to retrieve movies
paths:
  /movies:
    get:
      summary: List all movies
      parameters:
        - in: query
          name: prefix
          type: string
          required: false
          description: Prefix to filter movies
      responses:
        200:
          description: A list of movies
          schema:
            type: object
            properties:
              movies:
                type: array
                items:
                  $ref: '#/definitions/Movie'
definitions:
  Movie:
    type: object
    properties:
      name:
        type: string
      director:
        type: string
      image:
        type: string
